### ISSUE TITLE
Feature Request: automatically parse parameters and crawl 

### ISSUE THREAD

**Issue by royharoush** [stasinopoulos/commix#24]
Hi, 
Great tool ! 
My suggestion would be the following, and its bluntly stolen from sqlmap, but would be useful in commix.
~~1. accept an HTTP request in a file as a baseline for testing, map all the parameters in the request so you could use a parameter selection option ( -p parameter1,parameter2,).~~
~~2. accept an HTTP request in a file as a baseline for testing, and use a wildcard locator in the request file to point to where testing should be done (in sqlmap you can use * to specify where to test, which give you alot of space in testing area).~~
~~3. an option for the tool to spider the site and look for parameters and test them automatically. (again, stolen from sqlmap --forms --crawl)~~

Thanks and keep up the great work. 
Roy

**Comment by stasinopoulos** [comment]
@royharoush  thank you for your suggestion.

**Comment by stasinopoulos** [comment]
Hey @royharoush, I would like to inform you (about the number 2 in the features request) that from version 0.3b and on, commix supports an HTTP proxy logs parser (via the "-l" option) that gives the opportunity to the tester to specify the injectable  GET / POST parameter(s) or HTTP header(s) via the "INJECT_HERE" tag (that 's why i strikethrough the number 2).

![cylnvd8wcaamloy png large](https://cloud.githubusercontent.com/assets/5289251/14664704/e9b8e68a-06d5-11e6-90ca-9637003cf01b.png)

**Comment by stasinopoulos** [comment]
Hey @royharoush, since the commit https://github.com/stasinopoulos/commix/commit/2b2c09a1884f314cf53e795d44e43f34c1438eb1, the ability to check every GET parameter in the defined URL and/or every POST provided data has been added to commix as well as a parameter selection option ("-p" option) https://github.com/stasinopoulos/commix/commit/c1e29777e19d4632cb7c4246a382e43feedc9a7e. Moreover, I would like to inform you that as you have requested, the "INJECT_HERE" tag has been replaced with the "*" character https://github.com/stasinopoulos/commix/commit/ea3bd065aa7136f39aaf22810e835d4c835fec96.

**Comment by royharoush** [comment]
@stasinopoulos  you're awesome !

**Comment by stasinopoulos** [comment]
Hey @royharoush, since the last commit https://github.com/stasinopoulos/commix/commit/ba9873c34367c55cc9e3b0518028b56cbb4c6ca2, the ability for crawling of a given website (only for GET parameters), starting from the target url, has been added to commix.
